### PR TITLE
add ability to use Sentinel, also throw an exception if there's no co…

### PR DESCRIPTION
**Pull request by aaronflorey**
…nstraint

### CODE REVIEW

**Comment by Grimthorr** [comment]
Thanks, I'll add Sentinel support.

However, I don't think we want to throw an exception if `default_constraint_value` is null because the null value means that we'll use the built-in Laravel Authentication system (see comment at [config.php#L20](https://github.com/Grimthorr/laravel-user-settings/blob/master/config/config.php#L20)). I guess we could use 'auth' rather than null here though.

**Comment by Grimthorr** [comment]
Thanks, I'll add Sentinel support later if it's popular.

However, I don't think we want to throw an exception if `default_constraint_value` is null because the null value means that we'll use the built-in Laravel Authentication system (see comment at [config.php#L20](https://github.com/Grimthorr/laravel-user-settings/blob/master/config/config.php#L20)). I guess we could use 'auth' rather than null here though.

**Comment by aaronflorey** [comment]
I thought that would be the best place to put it, but i added that in because in my app i added the Settings::get('key') in on a artisan command, so we kept getting an error saying invalid sql syntax because Auth::check() was returning false so the constraint would return null and it ran the code anyway with WHERE id = null. So i added the exception in so it would throw an exception instead of a sql error.

**Comment by Grimthorr** [comment]
Ah I see, I've seen this before too; the default functionality of using `Auth` only works if the user is authenticated and the `Auth` service provider has actually been loaded by Laravel.

This is likely because the package assumes that settings only need to be accessed for authenticated users - but I see that might not always be the case.

I might have to change the way the `default_constraint_value` works to make it less janky :laughing:.

**Comment by aaronflorey** [comment]
Yeah exactly. I put the exception in so i'll be notified that i forgot to set the constraint.

Also, i needed to hardcore Sentinel in because i wasn't able to set it in the config.

**Pull request closed without merging**
